---
- name: Set up TESS Ecobee Controller and Monitor
  hosts: servers
  remote_user: pi
  become: yes
  vars_files:
    - vars.yaml
  
  tasks:
  - name: Update packages
    apt:
      update_cache=yes upgrade=yes
    tags:
      - upgrade_packages

  - name: Install necessary packages
    apt:
      pkg: "{{ item }}"
      state: present
    with_items:
      - git
      - python-dev
      - python-setuptools
    tags:
      - setup

  - name: Install pip
    easy_install:
      name: pip
      state: latest
    tags:
      - setup

  - name: Install virtualenv python package
    pip:
      name: virtualenv
    tags:
      - setup

  - name: Check for the virtualenv folder
    stat:
      path: /srv/pi/venv
    register: venv_folder
    tags:
      - setup

  - name: Create the srv/pi directory
    file:
      path: /srv/pi
      state: directory
      owner: pi
    when: venv_folder.stat.exists == False
    tags:
      - setup

  - name: Create a virtualenv for TESS
    command: virtualenv -p python3.4 /srv/pi/venv
    register: venv_setup
    when: venv_folder.stat.exists == False
    tags:
      - setup

  - name: Change owner of the folder
    file:
      path: /srv/pi
      state: directory
      recurse: yes
      owner: pi
    when: venv_folder.stat.exists == False
    tags:
      - setup

  - name: Create .ssh directory
    file:
      path: /home/pi/.ssh
      state: directory
    tags:
      - ssh

  - name: Create the SSH public key file for TESS Ecobee Controller
    copy:
      src: ~/.ssh/ecobee_rsa.pub
      dest: /home/pi/.ssh/ecobee_rsa.pub
      owner: pi
      mode: 0644
    tags:
      - ssh

  - name: Create the SSH private key file for TESS Ecobee Controller
    copy:
      src: ~/.ssh/ecobee_rsa
      dest: /home/pi/.ssh/ecobee_rsa
      owner: pi
      mode: 0600
    tags:
      - ssh

  - name: Install TESS Ecobee Controller code
    git:
      repo: 'https://github.com/VDL-PRISM/TESS.git'
      dest: /srv/pi/venv/TESS
      version: master
    become: yes
    become_user: pi
    register: code
    tags:
      - code
      - controller
      - monitor


  - name: Check for ecobee_controller.conf file for TESS Ecobee Controller
    stat:
      path: /srv/pi/venv/TESS/ecobee_controller.conf
    register: ecobee_controller_conf
    tags:
      - code
      - controller
      - ecobee

  - name: Set up ecobee_controller.conf file for TESS Ecobee Controller
    template:
      src: ecobee_controller.conf
      dest: /srv/pi/venv/TESS/ecobee_controller.conf
      owner: pi
      group: pi
      mode: 0644
    register: ecobee_controller
    when: ecobee_controller_conf.stat.exists == False
    tags:
      - code
      - controller
      - ecobee


  - name: Check for ecobee_monitor.conf file for TESS Ecobee Monitor
    stat:
      path: /srv/pi/venv/TESS/ecobee_monitor.conf
    register: ecobee_monitor_conf
    tags:
      - code
      - monitor
      - ecobee

  - name: Set up ecobee_monitor.conf file for TESS Ecobee Monitor
    template:
      src: ecobee_monitor.conf
      dest: /srv/pi/venv/TESS/ecobee_monitor.conf
      owner: pi
      group: pi
      mode: 0644
    register: ecobee_monitor
    when: ecobee_monitor_conf.stat.exists == False
    tags:
      - code
      - monitor
      - ecobee

  - name: Activate the virtualenv and install requirements
    shell: 
      cmd: |
        source /srv/pi/venv/bin/activate
        pip install -r /srv/pi/venv/TESS/TESS/requirements.txt
    args:
      executable: /bin/bash
    tags:
      - code
      - controller
      - monitor

  - name: Set up TESS controller service to run on boot
    template:
      src: tess-controller.service
      dest: /etc/systemd/system/tess-controller.service
    register: ctlservice
    tags:
      - systemd
      - controller

  - name: Restart the TESS Ecobee Controller service
    systemd:
      name: tess-controller.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    when: code.changed or ctlservice.changed or ecobee_controller.changed
    tags:
      - systemd
      - controller

  - name: Set up monitor service to run on boot
    template:
      src: tess-monitor.service
      dest: /etc/systemd/system/tess-monitor.service
    register: monservice
    tags:
      - systemd
      - monitor

  - name: Restart the TESS Ecobee Monitor service
    systemd:
      name: tess-monitor.service
      state: restarted
      enabled: yes
      daemon_reload: yes
    when: code.changed or monservice.changed or ecobee_monitor.changed
    tags:
      - systemd
      - monitor
